### PR TITLE
add auto-generator

### PR DESCRIPTION
**Pull request by cmeeren**
Continued from #12.

This time I have tried to use 4 spaces for indenting throughout. I have also added a couple of doc comments.

### CODE REVIEW

**Comment by moodmosaic** [comment]
Hm, this won't compile with F# 4.0. I'll try with F# 4.1 and see what happens. However, F# Hedgehog relies on F# 4.0, and I'm not sure if this will be an issue.

Here's the error message I'm getting (it's actually because of the `[<Struct>]` record type):

```
 [..]\hedgehog-fsharp-experimental\src\Hedgehog.Experimental\Gen.fs
       (176,19): error FS0927: The kind of the type specified by its attributes
       does not match the kind implied by its definition
```

**Comment by moodmosaic** [comment]
If I change `[<CLIMutable; Struct>]` to `[<CLIMutable>]` it builds successfully.

I'll have to investigate this further. FTR, [I'm still using Visual Studio 2015](https://gist.github.com/moodmosaic/91a33a361057b8cc08b85c18b6785fcf) (Update 3), with F# 4.0 and F# 4.1 (with Microsoft Build Tools 2017) installed.

What is your setup?

**Comment by cmeeren** [comment]
Strange. I notice while writing Hedgehog code that I don't have access to e.g. `Option.defaultValue`, which was [added in 4.1](https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-f-4-1-and-the-visual-f-tools-for-visual-studio-2017-2/), so I assume the solution is using 4.0 for me too, but IIRC I had no problem compiling. Will double-check.

**Comment by cmeeren** [comment]
Using VS2017, I expect with F#4.1.

**Comment by moodmosaic** [comment]
If you open a Git Bash window, what happens when you run `./build.sh`?

**Comment by cmeeren** [comment]
I'll try shortly. But why can't we use F#4.1? Is the F# version relevant at all for our users? I mean, once it's compiled it's just IL anyway, right?

**Comment by moodmosaic** [comment]
>But why can't we use F#4.1?

I guess we could. I'm just trying to figure out why it fails on my local 😰

**Comment by cmeeren** [comment]
I get entirely different errors. It builds fine with VS. When running build.sh, I get the following errors:

```
"C:\GH\fsharp-hedgehog-experimental\Hedgehog.Experimental.sln" (Rebuild target) (1) ->
"C:\GH\fsharp-hedgehog-experimental\src\Hedgehog.Experimental\Hedgehog.Experimental.fsproj" (Rebuild target) (2) ->
  C:\GH\fsharp-hedgehog-experimental\src\Hedgehog.Experimental\Hedgehog.Experimental.fsproj(42,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\FSharp\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is corre
       ct, and that the file exists on disk.


"C:\GH\fsharp-hedgehog-experimental\Hedgehog.Experimental.sln" (Rebuild target) (1) ->
"C:\GH\fsharp-hedgehog-experimental\tests\Hedgehog.Experimental.Tests\Hedgehog.Experimental.Tests.fsproj" (Rebuild target) (3) ->
  C:\GH\fsharp-hedgehog-experimental\tests\Hedgehog.Experimental.Tests\Hedgehog.Experimental.Tests.fsproj(51,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
```

**Comment by moodmosaic** [comment]
These errors you're getting are related to https://github.com/hedgehogqa/fsharp-hedgehog/issues/108.

**Comment by moodmosaic** [comment]
This resolves #5.

**Comment by moodmosaic** [comment]
Merged in d32b5fc. 🎉
